'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

import FormStep1 from './FormStep1/page'
import FormStep2 from './FormStep2/page'
import FormStep3 from './FormStep3/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
          
      </body>
    </html>
  )
}
